name: Deploy website

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Inject OpenAI API Key into index.html
      run: |
        sed -i 's/YOUR_API_KEY/${{ secrets.OPENAI_API_KEY }}/g' index.html
        sed -i 's/YOUR_API_KEY/${{ secrets.OPENAI_API_KEY }}/g' login.html

    - name: Commit changes
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add index.html login.html
        git commit -m 'Inject OpenAI API Key'
        git push

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./

